/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AiAnalyticsIndexRouteImport } from './routes/ai-analytics/index'
import { Route as AiAnalyticsAnomaliesRouteImport } from './routes/ai-analytics/anomalies'
import { Route as AiAnalyticsForecastingRouteImport } from './routes/ai-analytics/forecasting'
import { Route as AiAnalyticsRulRouteImport } from './routes/ai-analytics/rul'
import { Route as DashboardDetailsRouteImport } from './routes/dashboard/details'
import { Route as DashboardRealtimeRouteImport } from './routes/dashboard/realtime'
import { Route as MasterDataDeviceRouteImport } from './routes/master-data/device'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ReportsSummaryRouteImport } from './routes/reports/summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalyticsIndexRoute = AiAnalyticsIndexRouteImport.update({
  id: '/ai-analytics/',
  path: '/ai-analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalyticsAnomaliesRoute = AiAnalyticsAnomaliesRouteImport.update({
  id: '/ai-analytics/anomalies',
  path: '/ai-analytics/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalyticsForecastingRoute = AiAnalyticsForecastingRouteImport.update({
  id: '/ai-analytics/forecasting',
  path: '/ai-analytics/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalyticsRulRoute = AiAnalyticsRulRouteImport.update({
  id: '/ai-analytics/rul',
  path: '/ai-analytics/rul',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDetailsRoute = DashboardDetailsRouteImport.update({
  id: '/dashboard/details',
  path: '/dashboard/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRealtimeRoute = DashboardRealtimeRouteImport.update({
  id: '/dashboard/realtime',
  path: '/dashboard/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataDeviceRoute = MasterDataDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => MasterDataRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSummaryRoute = ReportsSummaryRouteImport.update({
  id: '/reports/summary',
  path: '/reports/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/master-data': typeof MasterDataRouteWithChildren
  '/users': typeof UsersRoute
  '/ai-analytics/anomalies': typeof AiAnalyticsAnomaliesRoute
  '/ai-analytics/forecasting': typeof AiAnalyticsForecastingRoute
  '/ai-analytics/rul': typeof AiAnalyticsRulRoute
  '/dashboard/details': typeof DashboardDetailsRoute
  '/dashboard/realtime': typeof DashboardRealtimeRoute
  '/master-data/device': typeof MasterDataDeviceRoute
  '/reports/summary': typeof ReportsSummaryRoute
  '/ai-analytics/': typeof AiAnalyticsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/master-data': typeof MasterDataRouteWithChildren
  '/users': typeof UsersRoute
  '/ai-analytics/anomalies': typeof AiAnalyticsAnomaliesRoute
  '/ai-analytics/forecasting': typeof AiAnalyticsForecastingRoute
  '/ai-analytics/rul': typeof AiAnalyticsRulRoute
  '/dashboard/details': typeof DashboardDetailsRoute
  '/dashboard/realtime': typeof DashboardRealtimeRoute
  '/master-data/device': typeof MasterDataDeviceRoute
  '/reports/summary': typeof ReportsSummaryRoute
  '/ai-analytics': typeof AiAnalyticsIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/master-data': typeof MasterDataRouteWithChildren
  '/users': typeof UsersRoute
  '/ai-analytics/anomalies': typeof AiAnalyticsAnomaliesRoute
  '/ai-analytics/forecasting': typeof AiAnalyticsForecastingRoute
  '/ai-analytics/rul': typeof AiAnalyticsRulRoute
  '/dashboard/details': typeof DashboardDetailsRoute
  '/dashboard/realtime': typeof DashboardRealtimeRoute
  '/master-data/device': typeof MasterDataDeviceRoute
  '/reports/summary': typeof ReportsSummaryRoute
  '/ai-analytics/': typeof AiAnalyticsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/master-data'
    | '/users'
    | '/ai-analytics/anomalies'
    | '/ai-analytics/forecasting'
    | '/ai-analytics/rul'
    | '/dashboard/details'
    | '/dashboard/realtime'
    | '/master-data/device'
    | '/reports/summary'
    | '/ai-analytics/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/master-data'
    | '/users'
    | '/ai-analytics/anomalies'
    | '/ai-analytics/forecasting'
    | '/ai-analytics/rul'
    | '/dashboard/details'
    | '/dashboard/realtime'
    | '/master-data/device'
    | '/reports/summary'
    | '/ai-analytics'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/master-data'
    | '/users'
    | '/ai-analytics/anomalies'
    | '/ai-analytics/forecasting'
    | '/ai-analytics/rul'
    | '/dashboard/details'
    | '/dashboard/realtime'
    | '/master-data/device'
    | '/reports/summary'
    | '/ai-analytics/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  MasterDataRoute: typeof MasterDataRouteWithChildren
  UsersRoute: typeof UsersRoute
  AiAnalyticsAnomaliesRoute: typeof AiAnalyticsAnomaliesRoute
  AiAnalyticsForecastingRoute: typeof AiAnalyticsForecastingRoute
  AiAnalyticsRulRoute: typeof AiAnalyticsRulRoute
  DashboardDetailsRoute: typeof DashboardDetailsRoute
  DashboardRealtimeRoute: typeof DashboardRealtimeRoute
  ReportsSummaryRoute: typeof ReportsSummaryRoute
  AiAnalyticsIndexRoute: typeof AiAnalyticsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analytics/': {
      id: '/ai-analytics/'
      path: '/ai-analytics'
      fullPath: '/ai-analytics/'
      preLoaderRoute: typeof AiAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analytics/anomalies': {
      id: '/ai-analytics/anomalies'
      path: '/ai-analytics/anomalies'
      fullPath: '/ai-analytics/anomalies'
      preLoaderRoute: typeof AiAnalyticsAnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analytics/forecasting': {
      id: '/ai-analytics/forecasting'
      path: '/ai-analytics/forecasting'
      fullPath: '/ai-analytics/forecasting'
      preLoaderRoute: typeof AiAnalyticsForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analytics/rul': {
      id: '/ai-analytics/rul'
      path: '/ai-analytics/rul'
      fullPath: '/ai-analytics/rul'
      preLoaderRoute: typeof AiAnalyticsRulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/details': {
      id: '/dashboard/details'
      path: '/dashboard/details'
      fullPath: '/dashboard/details'
      preLoaderRoute: typeof DashboardDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/realtime': {
      id: '/dashboard/realtime'
      path: '/dashboard/realtime'
      fullPath: '/dashboard/realtime'
      preLoaderRoute: typeof DashboardRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/device': {
      id: '/master-data/device'
      path: '/device'
      fullPath: '/master-data/device'
      preLoaderRoute: typeof MasterDataDeviceRouteImport
      parentRoute: typeof MasterDataRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/summary': {
      id: '/reports/summary'
      path: '/reports/summary'
      fullPath: '/reports/summary'
      preLoaderRoute: typeof ReportsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MasterDataRouteChildren {
  MasterDataDeviceRoute: typeof MasterDataDeviceRoute
}

const MasterDataRouteChildren: MasterDataRouteChildren = {
  MasterDataDeviceRoute: MasterDataDeviceRoute,
}

const MasterDataRouteWithChildren = MasterDataRoute._addFileChildren(
  MasterDataRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  MasterDataRoute: MasterDataRouteWithChildren,
  UsersRoute: UsersRoute,
  AiAnalyticsAnomaliesRoute: AiAnalyticsAnomaliesRoute,
  AiAnalyticsForecastingRoute: AiAnalyticsForecastingRoute,
  AiAnalyticsRulRoute: AiAnalyticsRulRoute,
  DashboardDetailsRoute: DashboardDetailsRoute,
  DashboardRealtimeRoute: DashboardRealtimeRoute,
  ReportsSummaryRoute: ReportsSummaryRoute,
  AiAnalyticsIndexRoute: AiAnalyticsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
